### ISSUE TITLE
Improvements made on the script 

### ISSUE THREAD

**Issue by xgrxmey** [Obcodelab/Mini-projects#2]
Improvements made on the script 

Logging Integration:

Added logging functionality to record program execution information and errors.
Logging is directed to a file named transcription.log for better debugging and tracking.
Dynamic AssemblyAI Installation:

Introduced a install_assemblyai function that checks if the AssemblyAI library is installed.
If not installed, it handles the installation process, imports the library, and returns it.
This ensures a seamless experience for users who may not have the library pre-installed.
API Key Validation:

Implemented validation for the API key format, ensuring it is of the expected length (64 characters).
If the API key is invalid, the program exits with an error message, preventing further execution.
File URL Validation:

Added validation to check if the provided file URL begins with "http," improving the reliability of the script.
Incorrectly formatted URLs trigger an error message and exit the program.
Enhanced Error Handling:

Enclosed the transcription process within a try...except block to catch and handle exceptions.
In case of transcription errors, the script provides informative error messages and logs error details to aid debugging.
User Feedback:

Improved user feedback by including clear and descriptive messages at each stage of program execution.
Users are informed of the progress and any issues that arise during transcription.

**Comment by Obcodelab** [comment]
Thanks a lot
